language: python

python:

  - "3.6"

before_script:

  - sudo wget https://bootstrap.pypa.io/get-pip.py
  - sudo python3 get-pip.py
  - sudo pip3 install codecov coverage
#  - sudo python clge_manager.py install SamplePlugin

script:

  - sudo python3 CLGETest.py

after_success:
  - sudo codecov
