language: python

matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: required
          python: "3.6"
          dist: trusty

        # Use generic language for osx
        - os: osx
          language: generic
          python: 
            - "3.6"
            - "2.7"

before_script:

  - sudo wget https://bootstrap.pypa.io/get-pip.py
  - sudo python3 get-pip.py
  - sudo -H pip3 install codecov coverage==4.3 codacy-coverage codeclimate-test-reporter
  - export CODACY_PROJECT_TOKEN=52384ccb8a50488da515d93ead374e27
  - export CODECLIMATE_REPO_TOKEN=9674fa1ab072a4ced75f6ee61433ad3e794c46cdd156ecd90ff7a5131aafc72b
#  - sudo python clge_manager.py install SamplePlugin

script:

  - sudo -H python3 CLGETest.py

after_success:
  - coverage xml
  - sudo codecov
  - sudo python-codacy-coverage -r coverage.xml
  - sudo codeclimate-test-reporter
