language: python

python:

  - "3.6"

before_script:

  - sudo pip install codecov coverage
#  - sudo python clge_manager.py install SamplePlugin

script:

  - sudo python CLGETest.py

after_success:
  - sudo codecov
